# Puerto del servidor Backend (usamos el 8080 por defecto)
server.port=8080

# Configuración de conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ecodigital?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# server.ssl.key-store=classpath:ecodigital-keystore.p12
# server.ssl.key-store-password=123456
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=sowad-ssl